/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../src/components/layout/AppHeader.vue')['default']
    BusinessComponentNode: typeof import('./../src/components/graph/BusinessComponentNode.vue')['default']
    ComponentDetails: typeof import('./../src/components/inspector/ComponentDetails.vue')['default']
    DataContractDetails: typeof import('./../src/components/inspector/DataContractDetails.vue')['default']
    DomainGroupNode: typeof import('./../src/components/graph/DomainGroupNode.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EvidenceList: typeof import('./../src/components/inspector/EvidenceList.vue')['default']
    ExternalBoundaryNode: typeof import('./../src/components/graph/ExternalBoundaryNode.vue')['default']
    FlowCanvas: typeof import('./../src/components/graph/FlowCanvas.vue')['default']
    FlowDetails: typeof import('./../src/components/inspector/FlowDetails.vue')['default']
    FlowKindFilter: typeof import('./../src/components/toolbar/FlowKindFilter.vue')['default']
    FolderActions: typeof import('./../src/components/toolbar/FolderActions.vue')['default']
    FolderScanProgress: typeof import('./../src/components/welcome/FolderScanProgress.vue')['default']
    FolderWelcome: typeof import('./../src/components/welcome/FolderWelcome.vue')['default']
    GraphActions: typeof import('./../src/components/toolbar/GraphActions.vue')['default']
    GraphEmptyState: typeof import('./../src/components/graph/GraphEmptyState.vue')['default']
    GraphLegend: typeof import('./../src/components/graph/GraphLegend.vue')['default']
    InspectorDrawer: typeof import('./../src/components/inspector/InspectorDrawer.vue')['default']
    LevelSwitcher: typeof import('./../src/components/toolbar/LevelSwitcher.vue')['default']
    ScenarioSelector: typeof import('./../src/components/toolbar/ScenarioSelector.vue')['default']
    ScenarioSidebar: typeof import('./../src/components/layout/ScenarioSidebar.vue')['default']
    SemanticFlowEdge: typeof import('./../src/components/graph/SemanticFlowEdge.vue')['default']
    SourceLinkItem: typeof import('./../src/components/inspector/SourceLinkItem.vue')['default']
    StatusBar: typeof import('./../src/components/layout/StatusBar.vue')['default']
    ValidationPanel: typeof import('./../src/components/inspector/ValidationPanel.vue')['default']
    VerificationBadge: typeof import('./../src/components/inspector/VerificationBadge.vue')['default']
    VerificationFilter: typeof import('./../src/components/toolbar/VerificationFilter.vue')['default']
  }
}
